# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='birthplace',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='current_mp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='current_sanity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='education',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_mp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_sanity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='residence',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
